### ISSUE TITLE
ELF section header type -2147483638

### ISSUE THREAD

**Issue by djipi** [hth313/Calypsi-tool-chains#29]
My homebrew project is using a bare metal platform (68000 with a couple of risc processors).
Using vlink linker, I got a warning message and would like to know more about it.
ELF section header type -2147483638.

This section is found either in my compiled code and in the Calypsi's library.

**Comment by hth313** [comment]
This is a vendor info section, there are two of these in the object files with number `0x8000000a` (this is the one you found) and `0x8000000b`.

It contains information about defined run-time attributes, section fragments (for pruning DWARF line programs), require attribute and section attributes like root/noroot/noreorder. It is information for the linker that is not otherwise carried in ELF which the linker use to detect module incompatibility and otherwise mainly to get the desired pieces from the C startup module automatically include or omitted to produce small binaries. 

The other vendor section contains compiler settings, such as code/data models, core and target settings. These are for the debugger, mainly to configure the behavior, e.g. of the expression evaluator.

**Comment by djipi** [comment]
Thank you for the feedbacks.
I think vlink is not able to handle such vendor info section. I'm able to generates an elf file but my emulator / debugger is not able to handle it yet. This is another story, and I will dig about it.
