### ISSUE TITLE
Please add a zip file for the Release build

### ISSUE THREAD

**Issue by djipi** [hth313/Calypsi-tool-chains#39]
The Windows installer (such as calypsi-68000-5.4.msi) is not signed so Windows may consider it as suspicious.
Will be good to have also a zip file containing the ready to use files.

**Comment by hth313** [comment]
I do not like the idea of using zip files when there is an installer for the platform. Signing would be the correct way forward. I have not looked at it, a quick search indicates that a certificate has to be purchased, is that the case?

**Comment by djipi** [comment]
> I do not like the idea of using zip files when there is an installer for the platform. Signing would be the correct way forward. I have not looked at it in depth, but a quick search indicates that a certificate has to be purchased, is that the case?
Thank you for the feedbacks.
Unfortunately, yes, you have to purchase a certificate, but it is costly (at least 200 USD to 300 USD a year).
I guess it is better to stay with the current installer.

**Comment by ProxyPlayerHD** [comment]
i'm also still very much for just having a zip file as an extra option as i've noted in a few other issues as well.

personally i think programs that don't REQUIRE installation onto a system (like setting up registry stuff, %appdata% folders, etc), shouldn't force users to install them and always provide a portable zip version as well.
and Calypsi C definitely doesn't require being installed in order to be functional, as it's completely self contained within in it's own folder. (only thing you "need" to do is update PATH and even that is completely optional, for example i never did it and still use it fine)

additionally if you want anything more complex than just the compiler on your C drive you need to mess with the installation afterwards anyways. in my case geting a new version of the compiler is:

1. download and run installer
2. copy the files to where i need them (my portable SSD)
3. unstall the compiler again because i don't like ghost programs in my apps list.

i'm very likely biased because usually i dislike installers in general (mainly because i put a lot of stuff on my portable SSD instead of my system drives). but i find installers only really worth it if have configuration options, like choosing the installation location, adding the program to %PATH%, etc.

and with the current very minimal installer, you need to do all of that yourself. which just makes it objectively worse than a zip file. because with a zip file you also need to set everything up yourself, main difference is that you don't need to wait for an installer to finish, find where it put the files (one time thing), and then uninstall it after you're done. you just extract it directly where you want it to be.

honestly i would be completely fine with only having an installer if it had the options mentioned above, and a little checkbox labeled "don't install, just copy the files" that you can tick so it doesn't actually add itself to your apps list. (basically turning the installer into an optionally self-extracting zip file)

**Comment by hth313** [comment]
I do not really want to have two ways to distribute the files for a platform. If the general idea is that the existing installer option is not good, then I can switch to using a `.zip` instead.

Now that Windows comes with a Linux subsystem (WSL), is the Windows specific binaries really needed?

**Comment by ProxyPlayerHD** [comment]
>I do not really want to have two ways to distribute the files for a platform. If the general idea is that the existing installer option is not good, then I can switch to using a .zip instead.

i'd say most if not all people would be fine with that.

>Now that Windows comes with a Linux subsystem (WSL), is the Windows specific binaries really needed?

yes.

because not every system has WSL installed, plus it seems to have some issues with external drives. so if you're like me and have the compiler on an external drive, then i would either be forced to install WSL on every system i want to use it on, or if WSL is installed do some manual work (or write a custom script) to find the drive letter, mount it in WSL, and then add the compiler to %PATH%.

a native windows version would be waaaay more convenient and accessible.

**Comment by djipi** [comment]
I would say.
Ok to have only a zip file.
And, yes, to keep the Windows version. Not everybody like Linux or have it installed.

Thank you again for the compiler.

**Comment by hth313** [comment]
I will change to a zip distribution, probably next release.

**Comment by djipi** [comment]
Thank you for the new version, but please add a Windows Release 5.5 zip file containing the ready to use files.

**Comment by hth313** [comment]
The 5.6 release is out.
