### ISSUE TITLE
Missing include/sys directory

### ISSUE THREAD

**Issue by djipi** [hth313/Calypsi-tool-chains#44]
In previous version, such as the 4.4, the directory was present (at least for the 68K).
It will be good to bring it back because projects may point on sys/time.h (or stat.h, types.h).

**Comment by hth313** [comment]
They were intentionally removed as they are not standard C.
I base the C library on the NuttX project which is a mix of C and POSIX, neither is complete.
Rather than trying to keep it in that spirit, I opted to change it towards being a standard C compliant library, thereby removing the POSIX parts, including the headers mentioned.

**Comment by djipi** [comment]
Thank you for the feedbacks.
